---
title: "P2"
output: html_document
date: "2024-06-11"
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(MASS)
library(entropy)
library(Rcpp)
library(RcppArmadillo)
library(ggpubr)
library(gridExtra)

library(cowplot)
options(dplyr.summarise.inform = FALSE)

sourceCpp('CAR_cpp.cpp')
```

```{r}
rcpp_loop(10,n,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.05,0.3,0.65),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)

mean <- matrix(0,6,9)


for (i in 1:6) {
  d <- seq(0,0.1,0.02)[i]
  mean[i,1:3] <- rcpp_loop(1000,500,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,1]
  mean[i,4:6] <- rcpp_loop(1000,500,4,2,3,2,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,1]
  mean[i,7:9] <- rcpp_loop(1000,500,4,2,3,3,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,1]
  
}

write.csv(mean,'p2_mean.csv',row.names = F)
```

mean_car

```{r}
mean_car <- matrix(0,6,9)


for (i in 1:6) {
  d <- seq(0,0.1,0.02)[i]
  mean_car[i,1:3] <- rcpp_loop(1000,500,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)[,1]
  mean_car[i,4:6] <- rcpp_loop(1000,500,4,2,3,2,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)[,1]
  mean_car[i,7:9] <- rcpp_loop(1000,500,4,2,3,3,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)[,1]
  
}

write.csv(mean_car,'p2_mean_car.csv',row.names = F)


read.csv('p2_mean_car.csv')
```

```{r}
data <- read.csv('p2_mean.csv')
data_car <- read.csv('p2_mean_car.csv')

color = c('Group1'="#00abf0",'Group2'="#eeb401",'Group3' = "#942d8d")
shape = c('M-CAR-ue'=1,'M-PS-ue'=2, 'Group3'=3)
```

```{r}
p1 <- ggplot()+
  scale_color_manual(values = color,breaks = names(color)) +
  scale_shape_manual(values = shape,breaks = names(shape)) +
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,1],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,1],
    color = names(color)[1],shape = names(shape)[1]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,4],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,4],
    color = names(color)[2],shape = names(shape)[1]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,7],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,7],
    color = names(color)[3],shape = names(shape)[1]
),size =2)+
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,1],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,1],
    color = names(color)[1],shape = names(shape)[2]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,4],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,4],
    color = names(color)[2],shape = names(shape)[2]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,7],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,7],
    color = names(color)[3],shape = names(shape)[2]
),size =2)+
  
labs(x =  'n',
y = 'Standard Deviation' ,
title = 'Overall',
color = NULL,shape=NULL) +
  scale_x_continuous(breaks = seq(0,0.1,0.02)) +
  scale_y_continuous(breaks = seq(-1,1,0.2),limits=c(-1,1)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(size = 8),
        panel.grid = element_blank(),
        plot.margin=unit(c(0, 0, 0, 0),'cm'))
```

```{r}
p2 <- ggplot()+
  scale_color_manual(values = color,breaks = names(color))+
  scale_shape_manual(values = shape,breaks = names(shape))+
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,2],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,2],
    color = names(color)[1],shape = names(shape)[1]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,5],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,5],
    color = names(color)[2],shape = names(shape)[1]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,8],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,8],
    color = names(color)[3],shape = names(shape)[1]
),size =2)+
  
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,1],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,1],
    color = names(color)[1],shape = names(shape)[2]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,4],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,4],
    color = names(color)[2],shape = names(shape)[2]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,7],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,7],
    color = names(color)[3],shape = names(shape)[2]
),size =2)+
  
   geom_line(aes(
    x = seq(0,0.1,0.02),
    y = 0),
    color = 'black') +
labs(x =  'n',
y = 'Standard Deviation' ,
title = 'Margin',
color = NULL,shape=NULL) +
  scale_x_continuous(breaks = seq(0,0.1,0.02)) +
  scale_y_continuous(breaks = seq(-1,1,0.2),limits=c(-1,1)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(size = 8),
        panel.grid = element_blank(),
        plot.margin=unit(c(0, 0, 0, 0),'cm'))
```

```{r}
p3 <- ggplot()+
  scale_color_manual(values = color,breaks = names(color))+
  scale_shape_manual(values = shape,breaks = names(shape))+
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,3],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,3],
    color = names(color)[1],shape = names(shape)[1]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,6],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,6],
    color = names(color)[2],shape = names(shape)[1]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,9],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,9],
    color = names(color)[3],shape = names(shape)[1]
),size =2)+
   geom_line(aes(
    x = seq(0,0.1,0.02),
    y = 0),
    color = 'black') +
  
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,1],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,1],
    color = names(color)[1],shape = names(shape)[2]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,4],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,4],
    color = names(color)[2],shape = names(shape)[2]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,7],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data_car[,7],
    color = names(color)[3],shape = names(shape)[2]
),size =2)+
  
labs(x =  'n',
y = 'Standard Deviation' ,
title = 'Stratum',
color = NULL,shape=NULL) +
  scale_x_continuous(breaks = seq(0,0.1,0.02)) +
  scale_y_continuous(breaks = seq(-1,1,0.2),limits=c(-1,1)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(size = 8),
        panel.grid = element_blank(),
        plot.margin=unit(c(0, 0, 0, 0),'cm'))
```

```{r}
ggsave('~/CAR/figure/P2.pdf',ggarrange(p1,p2,p3,common.legend = TRUE, legend = 'bottom',ncol = 3),height = 5, width = 15)
```
