---
title: "P3"
output: html_document
date: "2024-06-12"
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(MASS)
library(entropy)
library(Rcpp)
library(RcppArmadillo)
library(ggpubr)
library(gridExtra)

library(cowplot)
options(dplyr.summarise.inform = FALSE)

sourceCpp('CAR_cpp.cpp')
```

```{r}
sd_g1 <- matrix(0,6,9)

for (i in 1:6) {
  d <- seq(0,0.1,0.02)[i]
  sd_g1[i,1:3] <- rcpp_loop(1000,500,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)[,2]
  sd_g1[i,4:6] <- rcpp_loop(1000,500,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,2]
  sd_g1[i,7:9] <- rcpp_cr_loop(1000,500,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,2]
  
}

write.csv(sd_g1,'p3_g1.csv',row.names = F)
```

```{r}
sd_g2 <- matrix(0,6,9)

for (i in 1:6) {
  d <- seq(0,0.1,0.02)[i]
  sd_g2[i,1:3] <- rcpp_loop(1000,500,4,2,3,2,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)[,2]
  sd_g2[i,4:6] <- rcpp_loop(1000,500,4,2,3,2,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,2]
  sd_g2[i,7:9] <- rcpp_cr_loop(1000,500,4,2,3,2,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,2]
  
}

write.csv(sd_g2,'p3_g2.csv',row.names = F)
```

```{r}
sd_g3 <- matrix(0,6,9)

for (i in 1:6) {
  d <- seq(0,0.1,0.02)[i]
  sd_g3[i,1:3] <- rcpp_loop(1000,500,4,2,3,3,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0.2,wm = c(0.25,0.25),ws = 0.3,real_data)[,2]
  sd_g3[i,4:6] <- rcpp_loop(1000,500,4,2,3,3,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,2]
  sd_g3[i,7:9] <- rcpp_cr_loop(1000,500,4,2,3,3,prob,c(0.2,0.3,0.5),c(0.1+d,0.3,0.6-d),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)[,2]
  
}

write.csv(sd_g3,'p3_g3.csv',row.names = F)
```

```{r}
read.csv('p3_g2.csv')


rcpp_cr_loop(1000,500,4,2,3,1,prob,c(0.2,0.3,0.5),c(0.2,0.3,0.5),wo = 0,wm = c(0.5,0.5),ws = 0,real_data)
```

```{r}
data <- read.csv('p3_g1.csv')


ggplot()+
  scale_color_manual(values = color,breaks = names(color)) +
  scale_shape_manual(values = shape,breaks = names(shape)) +
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,1],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,1],
    color = names(color)[1],shape = names(shape)[1]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,4],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,4],
    color = names(color)[2],shape = names(shape)[2]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,7],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,7],
    color = names(color)[3],shape = names(shape)[3]
),size =2)+
labs(x =  'n',
y = 'Standard Deviation' ,
title = 'Overall',
color = NULL,shape=NULL) +
  scale_x_continuous(breaks = seq(0,0.1,0.02)) +
  scale_y_continuous(breaks = seq(0,0.6,0.1),limits=c(0,0.6)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(size = 8),
        panel.grid = element_blank(),
        plot.margin=unit(c(0, 0, 0, 0),'cm'))
```

```{r}
plot_p3 <- function(imb,data){
  color = c('M-CAR-ue'="#00abf0",'M-PS-ue'="#eeb401",'CR' = "#942d8d")
  shape = c('M-CAR-ue'=1,'M-PS-ue'=2, 'CR'=3)
  name <- c('Overall','Margin','Stratum')
  
  p <- ggplot()+
  scale_color_manual(values = color,breaks = names(color)) +
  scale_shape_manual(values = shape,breaks = names(shape)) +
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,imb],
    color = names(color)[1],
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,imb],
    color = names(color)[1],shape = names(shape)[1]
  ),size = 2) +
  
  geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,imb+3],
    color = names(color)[2]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,imb+3],
    color = names(color)[2],shape = names(shape)[2]
),size =2)+
  
    geom_line(aes(
    x = seq(0,0.1,0.02),
    y = data[,imb+6],
    color = names(color)[3]
  ),linetype = 'dashed') +
  geom_point(aes(
    x = seq(0,0.1,0.02),
    y = data[,imb+6],
    color = names(color)[3],shape = names(shape)[3]
),size =2)+
labs(x =  'n',
y =  'SD',
title = name[imb],
color = NULL,shape=NULL) +
  scale_x_continuous(breaks = seq(0,0.1,0.02)) +
  scale_y_continuous(breaks = seq(0,0.6,0.1),limits=c(0,0.6)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.y = element_text(size = 8),
        panel.grid = element_blank(),
        plot.margin=unit(c(0, 0, 0, 0),'cm'))
  
  return(p)

}


data1 <- read.csv('p3_g1.csv')
data2 <- read.csv('p3_g2.csv')
data3 <- read.csv('p3_g3.csv')
```

```{r}
p <- ggarrange(plot_p3(1,data1),plot_p3(2,data1), plot_p3(3,data1),plot_p3(1,data2), plot_p3(2,data2),plot_p3(3,data2),plot_p3(1,data3), plot_p3(2,data3), plot_p3(3,data3)  ,common.legend = TRUE, legend = 'bottom',ncol = 3,nrow = 3)


ggsave('~/CAR/figure/P3.pdf',p,height = 15, width = 15 )

```
